# Generated by Django 2.2.5 on 2020-12-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peopelinfo',
            table='peopleinfo',
        ),
    ]
